CREATE TABLE IF NOT EXISTS emprestimos(
    id INT AUTO_INCREMENT PRIMARY KEY,
    idUsuario INT NOT NULL,
    idLivro INT NOT NULL,
    dataEmprestimo TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (idUsuario)
    REFERENCES usuarios(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,

    FOREIGN KEY (idLivro)
    REFERENCES livros(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);