CREATE TABLE IF NOT EXISTS emprestimos(
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome_usuario VARCHAR(30) NOT NULL,
    nome_livro VARCHAR(30) NOT NULL,
    data_emprestimo TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (nome_usuario)
    REFERENCES usuarios(nome)
    ON UPDATE CASCADE
    ON DELETE CASCADE,

    FOREIGN KEY (nome_livro)
    REFERENCES livros(nome)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);