CREATE TABLE IF NOT EXISTS emprestimos(
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_usuario INT NOT NULL,
    id_livro INT NOT NULL,
    data_emprestimo TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (id_usuario)
    REFERENCES usuarios(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,

    FOREIGN KEY (id_livro)
    REFERENCES livros(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);